# -*- coding: utf-8 -*-
"""testeComArquivoTxtPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-ZWv2rbMFqQzUVkrykH4RMHfy6FG7Z0
"""

import pandas as pd

url_dados = 'https://github.com/helenharumi/testePython/blob/master/dados/04-2020.txt?raw=true'

lista=pd.read_table(url_dados, sep=';')
lista

"""

Mostra as 5 primeiras linhas
"""

lista.head()

"""Número de linhas e coluna"""

lista.shape

lista['despacho'].value_counts()

lista['despacho'].value_counts().plot.barh()

lista['despacho'].unique()

lista['despacho'].value_counts()

lista['despacho'].value_counts(normalize = True)

lista.describe()

pd.crosstab(lista['especie'], lista['sexo'])