# -*- coding: utf-8 -*-
"""testePython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/109b1SbI5_nN76puwqKI5UZhHYFUuCNTh
"""

import pandas as pd

url_dados = 'https://github.com/helenharumi/testePython/blob/master/dados/04-2020.csv?raw=true'

lista = pd.read_csv(url_dados, sep=';')
lista

"""

Mostra as 5 primeiras linhas
"""

lista.head()

"""Número de linhas e coluna"""

lista.shape

lista['despacho'].value_counts().plot.bar()

lista['despacho'].unique()

lista['despacho'].value_counts()

lista['despacho'].value_counts(normalize = True)

lista.describe()

pd.crosstab(lista['especie'], lista['sexo'])